Create ens profile setting
payton/django-siwe-auth pull request #23
Opened 2022-06-04 00:57 UTC by pconerly

This would solve my issue https://github.com/payton/django-siwe-auth/issues/19

I added an option, CREATE_ENS_PROFILE_ON_AUTHN. I tried to emulate CREATE_GROUPS_ON_AUTHN without changing the current behavior for django-siwe-auth users, which is why I default CREATE_ENS_PROFILE_ON_AUTHN to True in backends.py.

I also added some documentation to README.md, but you could cherry-pick that commit and remove a line to include it without the rest of the code here.

2022-06-04 11:16 UTC, payton requested changes
Looks great @pconerly. Just a left a few minor changes to be made.

2022-06-04 11:16 UTC, payton commented on README.md
> +   CREATE_GROUPS_ON_AUTHN = True # defaults to False
nit: Set to False as per comment

2022-06-04 11:16 UTC, payton commented on README.md
> +#### django-siwe-auth specific options in settings.py:
Please separate these options out into two sections: django-siwe-auth options and django-native options. I want to differentiate between which configurations are custom from django-siwe-auth.

Django Native: AUTH_USER_MODEL, AUTHENTICATION_BACKENDS, LOGIN_URL, SESSION_COOKIE_AGE
Django SIWE Auth: CREATE_GROUPS_ON_AUTHN, CREATE_ENS_PROFILE_ON_AUTHN, CUSTOM_GROUPS, PROVIDER

2022-06-04 11:16 UTC, payton commented on siwe_auth/backend.py
> +    name: str = ""
Let's make these both default to `None`. The current behavior is that `ENS.fromWeb3(w3).name(address=ethereum_address)` will return `None` if a given request is not found.

2022-06-04 20:29 UTC, pconerly commented
The changes you asked for make sense, thanks for reviewing it. I just pushed a commit with those changes

2022-06-05 00:07 UTC, payton approved these changes
Awesome. Thanks @pconerly !

2022-06-05 00:07 UTC, merged